import Head from "next/head";
import Image from "next/image";
import Button from "../components/Button";
import Circles from "../components/Circles";
import Links from "../components/Links";
import Waves from "../components/Waves";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dream your film now, without limits.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo.svg" />
      </Head>

      <main className="main">
        <Links active="home" />

        <div className={styles.content}>
          <Image src="/assets/logo.svg" alt="Logo" width={60} height={90} />
          <h1>
            Dream{" "}
            <span className="color-3">
              your <br /> Film{" "}
            </span>
            <span className="color-1">Now,</span>
          </h1>
          <h3>Without limits.</h3>
          <Button link="https://forms.gle/KfVsqh61RTD8pCDk9">
            Register Now
          </Button>
        </div>

        <Waves />

        <div className={styles.lines}></div>

        <Circles />
      </main>
    </div>
  );
}
